const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map();
const get=id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',hidden:false,classList:{toggle(){},add(){}},addEventListener(){}});return elements.get(id)};
const payload={live:true,age_seconds:0,server_time:new Date().toISOString(),performance:{markets_tracked:2,markets_settled:1,unique_graded:1,win_rate:1},markets:[{asset:'BTC',title:'<img src=x onerror=alert(1)>',seconds_left:100,model_probability:.6,market_probability:.5,spot:100,target:99,setup_score:75,action:'LEAN YES',confidence:'HIGH',quality_notes:[],yes_ask:.5,no_ask:.6,edge:.1}]};
let calls=0;
const ctx=vm.createContext({console,Date,Number,String,Math,AbortController,AbortSignal,setTimeout:()=>1,clearTimeout(){},setInterval(){},window:{addEventListener(){}},document:{hidden:false,getElementById:get,querySelectorAll:()=>[],addEventListener(){}},fetch:async()=>{calls++;return {ok:true,json:async()=>payload}}});
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const script=html.split('<script>')[1].split('</script>')[0];
vm.runInContext(script,ctx);
const run=s=>vm.runInContext(s,ctx);
(async()=>{
 await new Promise(setImmediate);
 assert.equal(get('marketCount').textContent,1);
 ctx.paperFixture={summary:{starting_bank:1000,net_pnl:-5.27,settled:1,pending:1,roi:-1,max_realized_drawdown:5.27,cash:989.46,pending_cost:5.27,settled_rounds:1,fees:.35,slippage_cost:.2},breakdowns:{asset:[{label:'<img src=x>',settled:1,trades:2,win_rate:0,net_pnl:-5.27}]},rows:[{asset:'BTC',side:'YES',contracts:10,fill_price:.51,cost:5.27,fee:.17,pnl:null,captured_at:new Date().toISOString(),seconds_left:200}],equity_curve:[{equity:994.73}]};
 run('paperRender(paperFixture)');
 assert(get('paperSummary').innerHTML.includes('$-5.27'));
 assert(get('paperSummary').innerHTML.includes('<svg'));
 assert(get('paperBreakdowns').innerHTML.includes('&lt;img'));
 assert(!get('paperBreakdowns').innerHTML.includes('<img'));
 assert(get('paperTrades').innerHTML.includes('PENDING'));
 ctx.paperFixture.equity_curve=[];ctx.paperFixture.summary.settled=0;
 run('paperRender(paperFixture)');
 assert(get('paperSummary').innerHTML.includes('No settled paper results yet'));
 assert(!get('paperSummary').innerHTML.includes('<svg'));
 assert(get('app').innerHTML.includes('&lt;img'));
 assert(!get('app').innerHTML.includes('<img'));
 run('lastReceipt=Date.now()-30000;render()');
 assert(get('app').innerHTML.includes('STALE · WAIT'));
 run('lastReceipt=Date.now();data[0].seconds_left=0;render()');
 assert(get('app').innerHTML.includes('EXPIRED · WAIT'));
 run('filter="FINAL5"');assert.equal(run('filtered().length'),1);
 run('busy=true');const previous=calls;await run('load()');assert.equal(calls,previous);
 run('busy=false');ctx.fetch=async()=>{throw Error('offline')};await run('load()');
 assert.equal(get('status').textContent,'OFFLINE');assert.equal(run('data.length'),1);
 assert(get('app').innerHTML.includes('STALE · WAIT'));
 console.log('Frontend checks passed: rendering, title escaping, stale/expired suppression, filters, concurrent refresh guard, offline retention.');
})();
